pipelines:
  default:
    - step:
        script:
          - echo "Sonar pipeline, baby!"
          - curl --insecure -OL https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-2.6.1.zip
          - unzip sonar-scanner-2.6.1.zip
          - ./sonar-scanner-2.6.1/bin/sonar-scanner -Dsonar.projectKey=NGMOD -Dsonar.organization=spy8681-bitbucket -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a6c2f83b9ee15bafc0b75236bb67c6cfb6ff8a82