pipelines:
  default:
    - step:
        script:
          - echo "Sonar pipeline, baby!"
          - curl --insecure -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
          - unzip sonar-scanner-cli-3.2.0.1227-linux.zip
          - ./sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner -Dsonar.projectKey=NGMOD -Dsonar.organization=$ORG -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN